# Generated by Django 5.2.4 on 2025-07-23 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('recommended_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='skills.skillcategory')),
                ('recommended_skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='skills.skill')),
                ('required_all', models.ManyToManyField(related_name='rules_all', to='skills.skillcategory')),
                ('required_any', models.ManyToManyField(related_name='rules_any', to='skills.skillcategory')),
            ],
        ),
    ]
